module.exports = {
    worldNames: {
        na: [
            "Anvil Rock",
            "Blackgate",
            "Borlis Pass",
            "Crystal Desert",
            "Darkhaven",
            "Devona's Rest",
            "Dragonbrand",
            "Ehmry Bay",
            "Eredon Terrace",
            "Ferguson's Crossing",
            "Fort Aspenwood",
            "Gate of Madness",
            "Henge of Denravi",
            "Isle of Janthir",
            "Jade Quarry",
            "Kaineng",
            "Maguuma",
            "Northern Shiverpeaks",
            "Sanctum of Rall",
            "Sea of Sorrows",
            "Sorrow's Furnace",
            "Stormbluff Isle",
            "Tarnished Coast",
            "Yak's Bend"
        ],
        eu: [
            "Abaddon's Mouth [DE]",
            "Arborstone [FR]",
            "Augury Rock [FR]",
            "Aurora Glade",
            "Baruch Bay [SP]",
            "Blacktide",
            "Desolation",
            "Drakkar Lake [DE]",
            "Dzagonur [DE]",
            "Elona Reach [DE]",
            "Far Shiverpeaks",
            "Fissure of Woe",
            "Fort Ranik [FR]",
            "Gandara",
            "Gunnar's Hold",
            "Jade Sea [FR]",
            "Kodash [DE]",
            "Miller's Sound [DE]",
            "Piken Square",
            "Ring of Fire",
            "Riverside [DE]",
            "Ruins of Surmia",
            "Seafarer's Rest",
            "Underworld",
            "Vabbi",
            "Vizunah Square",
            "Whiteside Ridge"
        ]
    }
}