module.exports = {
    worldNames: [
        "Abaddon's Mouth [DE]",
        "Anvil Rock",
        "Arborstone [FR]",
        "Augury Rock [FR]",
        "Aurora Glade",
        "Baruch Bay [SP]",
        "Blackgate",
        "Blacktide",
        "Borlis Pass",
        "Crystal Desert",
        "Darkhaven",
        "Desolation",
        "Devona's Rest",
        "Dragonbrand",
        "Drakkar Lake [DE]",
        "Dzagonur [DE]",
        "Ehmry Bay",
        "Elona Reach [DE]",
        "Eredon Terrace",
        "Far Shiverpeaks",
        "Ferguson's Crossing",
        "Fissure of Woe",
        "Fort Aspenwood",
        "Fort Ranik [FR]",
        "Gandara",
        "Gate of Madness",
        "Gunnar's Hold",
        "Henge of Denravi",
        "Isle of Janthir",
        "Jade Quarry",
        "Jade Sea [FR]",
        "Kaineng",
        "Kodash [DE]",
        "Maguuma",
        "Miller's Sound [DE]",
        "Northern Shiverpeaks",
        "Piken Square",
        "Ring of Fire",
        "Riverside [DE]",
        "Ruins of Surmia",
        "Sanctum of Rall",
        "Sea of Sorrows",
        "Seafarer's Rest",
        "Sorrow's Furnace",
        "Stormbluff Isle",
        "Tarnished Coast",
        "Underworld",
        "Vabbi",
        "Vizunah Square [FR]",
        "Whiteside Ridge",
        "Yak's Bend"
    ]
}