module.exports = {
    "Anvil Rock": [],
    "Borlis Pass": [],
    "Yak's Bend": [],
    "Henge of Denravi": [],
    "Maguuma": [],
    "Sorrow's Furnace": [],
    "Gate of Madness": [],
    "Jade Quarry": [],
    "Fort Aspenwood": [],
    "Ehmry Bay": [],
    "Stormbluff Isle": [],
    "Darkhaven": [],
    "Sanctum of Rall": [],
    "Crystal Desert": [],
    "Isle of Janthir": [],
    "Sea of Sorrows": [],
    "Tarnished Coast": [],
    "Northern Shiverpeaks": [],
    "Blackgate": [],
    "Ferguson's Crossing": [],
    "Dragonbrand": [],
    "Kaineng": [],
    "Devona's Rest": [],
    "Eredon Terrace": [],
    "Fissure of Woe": [],
    "Desolation": [],
    "Gandara": [],
    "Blacktide": [],
    "Ring of Fire": [],
    "Underworld": [],
    "Far Shiverpeaks": [],
    "Whiteside Ridge": [],
    "Ruins of Surmia": [],
    "Seafarer's Rest": [],
    "Vabbi": [],
    "Piken Square": [],
    "Aurora Glade": [],
    "Gunnar's Hold": [],
    "Jade Sea [FR]": [],
    "Fort Ranik [FR]": [],
    "Augury Rock [FR]": [],
    "Vizunah Square [FR]": [],
    "Arborstone [FR]": [],
    "Kodash [DE]": [],
    "Riverside [DE]": [],
    "Elona Reach [DE]": [],
    "Abaddon's Mouth [DE]": [],
    "Drakkar Lake [DE]": [],
    "Miller's Sound [DE]": [],
    "Dzagonur [DE]": [],
    "Baruch Bay [SP]": []

}